
---
- name: Pull docker image of Calculator
  hosts: all
 
  tasks:
    - name: Pull docker image
      docker_image:
        name: matehate/debateleaguebackend
        source: pull
        force_source: yes
